# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sample-app-deployment
spec:
  selector:
    matchLabels:
      app: prometheus-sample-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: prometheus-sample-app
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: prometheus-sample-app
          image: rlachhman/promsample:1.0.0-amd64
          imagePullPolicy: Always
          command:
            - "/bin/main"
          args:
            - "--metric_count=1"
          ports:
            - containerPort: 8080